#
# Source code address
# https://hub.docker.com/u/cuongtransc/
#
# Syntax: https://docs.docker.com/compose/compose-file/
#

version: "2"

services:
    skyhook:
        image: cuongtransc/skyhook:0.1
#        environment:
#             - NODE_ENV=production
        ports:
            - "8080:8080"
        networks:
            - comp_default
        hostname: skyhook
        domainname: devopsz.com
        cpu_shares: 1024
        mem_limit: 100M
        # privileged: true
        # restart: always           # other choice: on-failure:3
        # stdin_open: true
        # tty: true
        logging:
            driver: "json-file"
            options:
                max-size: "100M"
                max-file: "3"

networks:
    comp_default:
        external: true

